version: "3.8"

services:
  minecraft-server:
    image: itzg/minecraft-server:latest
    container_name: minecraft-server
    ports:
      - 25565:25565
      - 25575:25575
    environment:
      SERVER_NAME: "Dockerized-Minecraft-Server"
      EULA: "TRUE"
      MODE: "creative"
      LEVEL_TYPE: "flat"
      ENABLE_RCON: "TRUE"
      ONLINE_MODE: "FALSE"
      RCON_PASSWORD: "secret"
      RCON_PORT: 25575
      SERVER_PORT: 25565
    restart: unless-stopped
  streamcraftremote:
    image: streamcraftremote
    container_name: streamcraftremote
    build: .
    ports:
      - 3210:3210
    restart: unless-stopped
